# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DiagLeg
                                 A QGIS plugin
 This plugin allows to create a legend, for diagrams generated through the "Overlay" tab of the layer properties.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-16
        copyright            : (C) 2023 by doublebyte
        email                : info@doublebyte.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DiagLeg class from file DiagLeg.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .diagleg import DiagLeg
    return DiagLeg(iface)
